modLoader="javafml"

loaderVersion="[47,)"

license="MIT"

[[mods]]

modId="design_decor"

version="0.4.1b"

displayName="Create: Design n' Decor"

logoFile="logo.png"


authors="DrMangoTea, Milky, Luna, Pepa, Spydnel"

description='''
dave's building extended but way better :3
'''

[[dependencies.design_decor]]

    modId="forge"

    mandatory=true

    versionRange="[47,)"

    ordering="NONE"

    side="BOTH"
[[dependencies.design_decor]]
modId="create"
mandatory=true
versionRange="[6.0.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.design_decor]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
